- mode : image
  images_path: ./data/imgs_MOV03478
  groundtruth_path: ./layout/mov03478.csv
  model_name: SSDLite
  adapter_name: AdapterSSDLite
  path_classes: ./models/COCO_V1_classes.txt
  batch_size: 1
  confidence: 0.5
  nms_threshold: 0.4
  scale: 1.0      # placeholder
  size: 312 312   # placeholder
  mean:           # placeholder
  swapRB:         # placeholder