- mode : image
  images_path: ./data/imgs_MOV03478
  groundtruth_path: ./layout/mov03478.csv
  model_name: yolox_tiny
  adapter_name: AdapterYOLOX
  path_weights: ./models/yolox-tiny.onnx      # from openvinotoolkit/open_model_zoo repo
  path_classes: ./models/COCO_V1_classes.txt
  batch_size: 1
  confidence: 0.5
  nms_threshold: 0.45
  scale: 0.00392156862745098  # 1/255
  size: 416 416
  mean:
  swapRB: True